Product details
JevIv/learn_project pull request #6
Opened 2020-06-11 19:20 UTC by JevIv

2020-06-13 19:22 UTC, technogleb requested changes

2020-06-13 19:22 UTC, technogleb commented on url_scraping.py
> +    r = requests.get(url)
Здесь тоже нужна проверка raise_for_status.

2020-06-13 19:22 UTC, technogleb commented on url_scraping.py
> +	if html:
Не проще ли, наоборот, разобрать случай когда html нет, и вызвать exception или вернуть что-либо эдакое, чем писать всю логику функции внутри сдвинутого еще на один tab вправо блока, увеличивая вложенность кода?

2020-06-13 19:22 UTC, technogleb commented on url_scraping.py
> +			for product in all_products:
Кхм, может быть у меня баг, но тут синтаксическая ошибка - строчка смещена на таб вправо

2020-06-13 19:22 UTC, technogleb commented on url_scraping.py
> +			url = "https://www.avito.ru" + url
По-хорошему тут надо использовать что-то вроде этого https://stackoverflow.com/questions/8223939/how-to-join-absolute-and-relative-urls. Вдруг у тебя в url не будет слеша в начале?

2020-06-13 19:22 UTC, technogleb commented on url_check.py
> +
Две строчки отступа.

2020-06-13 19:22 UTC, technogleb commented on product_details.py
> +def get_html(url):
Эту функцию ты уже написал в одном месте, зачем ее лишний раз переписывать, вместо этого надо импортировать.
from learn_project.url_scrapping import get_html

2020-06-13 19:22 UTC, technogleb commented on product_details.py
> + 		try:															#все поиски ниже ведутся в нём
Посмотри документацию beautifulsoup, наверняка есть возможность возвращать дефолтное значение, если нужный документ не был найден. Миллион try, except так себе решение, оставим на крайняк.

2020-06-13 19:22 UTC, technogleb commented on product_details.py
> + 		except:
Но даже если ты делаешь except, нужно указывать какое именно исключение ты обрабатываешь. Оставлять просто except в широком смысле считается моветоном.

2020-06-13 19:22 UTC, technogleb commented on product_details.py
> +	 	except:
Вот здесь как раз точно except нужно указать конкретно, у тебя есть довольно большая логика внутри try, и если ты будешь просто так отделываться except-ом, ты можешь не понять, если у тебя вдруг появится ошибка конкретно в твоем коде, а не в том, чего ты хочешь избежать.

2020-06-13 19:22 UTC, technogleb commented on product_details.py
> + 	if html:
Опять, лучше написать if not html, см коммент ниже

2020-06-13 19:22 UTC, technogleb commented on product_details.py
> +	 	details = {			#словарь в который собираются данные
Ты видимо забыл его вернуть) функция почему-то ничего не возвращает.

2020-06-13 19:25 UTC, technogleb commented on product_details.py
> + 		try:															#все поиски ниже ведутся в нём
Правильно я понимаю, что эту логику ты делаешь в случае, если bs ничего не найдет с таким классом?
Тогда вот из документации, собственно
<img width="762" alt="image" src="https://user-images.githubusercontent.com/20286001/84577444-c778cf00-adc4-11ea-8508-36c4d30f4ec4.png">

2020-06-14 08:08 UTC, JevIv commented on product_details.py
> + 		try:															#все поиски ниже ведутся в нём
Да, всё верно, мне показалось, что будет лучше, если вместо None вернёт пустую строку.

2020-06-14 11:52 UTC, technogleb approved these changes
Линтер тоже в IDE встрой пожалуйста.

2020-06-14 11:52 UTC, merged